name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run-tests:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    
    name: Tests 
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Install dependencies
        run: python -m pip install -r requirements.txt

      - name: Install Ubuntu Playwright browsers
        if: matrix.os == 'ubuntu-latest'
        run: python -m playwright install --with-deps

      - name: Install Windows Playwright browsers
        if: matrix.os == 'windows-latest'
        run: python -m playwright install

      - name: Add repo to PYTHONPATH
        run: echo "PYTHONPATH=$PWD" >> $GITHUB_ENV

      - name: Start Ubuntu Flask app
        if: matrix.os == 'ubuntu-latest'
        env:
          PYTHONPATH: ${{ github.workspace }}
        shell: bash
        run: python app.py & sleep 5

      - name: Start Windows Flask app
        if: matrix.os == 'windows-latest'
        env:
          PYTHONPATH: ${{ github.workspace }}
        shell: pwsh
        run: |
          Start-Process python app.py
          Start-Sleep -Seconds 5

      - name: Run E2E tests
        if: matrix.os != 'macos-latest'
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: pytest -q tests/test_e2e.py

      - name: Run tests
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: pytest -q --ignore=tests/test_e2e.py

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}
